alexeygrigorev/data-science-interviews

- theory.md
Added answers for:
1) Is accuracy always a good metric
2) What is confusion tables and cell in confusion table
> Add Confusion Matrix and why not Accuracy

- theory.md
> Add Normal equations answer

- theory.md
Hi Alexey, 
thank you for your great initiative. I have added the answers to the clustering section with the best of my knowledge. Please let me know if you want more information to be included in the section (e.g. further algorithms, gap statistics method to determine the number of cluster for k-mean or anything else :))
> added answers to clustering section

- theory.md
Several regression models have been added to the answer.
> regression models answer

- theory.md
Hopefully the explanations aren't too long but if so, just let me know and I could edit! Or if you'd like, feel free to make changes yourself as well! :)
> update to parameter tuning answers (grid search, random search, and bo)

- theory.md
Added answers to the following questions:
- Why do we need one-hot encoding? ‍⭐️
- How does L2 regularization look like in a linear model? ‍⭐️
- Can we use L1 regularization for feature selection? ‍⭐️
- What is dropout? Why is it useful? How does it work? ‍⭐️
- If you have a sentence with multiple words, you may need to combine multiple word embeddings into one. How would you do it? ‍⭐️
- What is precision and recall at k? ‍⭐️
> Added several answers

- theory.md
Answered to questions regarding Data Science
> Answers to Data Science Question

- theory.md
- Provided an answer for "what do we do with categorical variables"
- Listed popular encoding techniques
> An answer for handling categorical variables

- theory.md
I have added answers to two questions on regularization.
> added answers to regularization

- technical.md
I added a recursive solution to the factorial function. It's just a bit neater than the non-recursive one. It does assume a non-negative input (though you can easily add some check for n < 0 if you want).
> Add recursive solution factorial

- technical.md
please the first and the second commit are the same but the first don't have the  comments so let's forget the first
> Fibonacci Question in Algorithme section

- technical.md
- small fix on fizzbuzz (upper-lower case)
- a solution on std dev
- a solution on counter
- a solution on top counter
- a solution on rle
- a solution on idf
- 3 solution on fibonacci
- a solution on most frequent outcome
- a solution on reverse a linked list
- a solution on flip a binary tree
- a solution on binary search
- 2 solution on deduplication
- 2 solution on intersection
- 2 solution on union
- a solution on addition
- a solution on check is binary search tree
> add some coding and algorithm solutions

- theory.md
1. Add answers to _What is the ROC curve? When to use it_
ROC stands for *Receiver Operating Characteristics*. 
2. Answered the question of _What is AUC (AU ROC)? When to use it?_ 
AUC stands for *Area Under the ROC Curve*. ROC is a probability curve and AUC represents degree or measure of separability. It's used when we need to value how much model is capable of distinguishing between classes.  The value is between 0 and 1, the higher the better.
AUC score is the value of *Area Under the ROC Curve*. 
3. Answered the question of  _How to interpret the AU ROC score?_
If we assume ROC curve consists of dots, $\{(x_1, y_1), (x_2, y_2), \cdots, (x_m,y_m)\}$, then
$$
AUC = \frac{1}{2} \sum_{i=1}^{m-1}(x_{i+1}-x_i)\cdot (y_i+y_{i+1})
$$
An excellent model has AUC near to the 1 which means it …
> add answers to theory.md - what is auc & how to interpret auc score

- theory.md
Answered questions :
- What’s a convolutional layer?
- Why do we actually need convolutions? Can’t we use fully-connected layers for that?
- What’s pooling in CNN? Why do we need it?
- How does max pooling work? Are there other pooling techniques?
- When would you use Adam and when SGD?
- What is ReLU? How is it better than sigmoid or tanh?
Maybe some more question which I have forgotten.
> Answers to some questions

- awesome.md
- technical.md
This is a very common solution in Dynamic Programming: `Top-down + memorization`
Problem -  **Fibonacci**. Return the n-th Fibonacci number, which is computed using this formula:
* F(0) = 0
* F(1) = 1
* F(n) = F(n-1) + F(n-2)
* The sequence is: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Answers - 
`def fibonacci4(n):
#Top down + memorization (dictionary), complexity = O(n)
dic = {1:1, 2:2}
if n not in dic:
dic[n] = fibonacci4(n-1) + fibonacci4(n-2)
return dic[n]
def fibonacci5(n):
#Top down + memorization (list), complexity = O(n) 
if n == 1:
return 1
dic = [-1 for i in range(n)]
dic[0], dic[1] = 1, 2
def helper(n, dic):
if dic[n] < 0:
dic[n] = helper(n-1, dic) + helper(n-2, dic)
return dic[n]
return helper(n-1, dic)`
> add answers to technical.md, fibonacci problem

- theory.md
Hello Alex! Today I got an interview from Microsoft Research, and thanks a lot to your repository!!!
I add answers to theory.md
1. What happens when we have correlated features in our data?
In random forest, since random forest samples some features to build each tree, the information contained in correlated features is twice as much likely to be picked than any other information contained in other features. 
In general, when you are adding correlated features, it means that they linearly contains the same information and thus it will reduce the robustness of your model. Each time you train your model, your model might pick one feature or the other to "do the same job" i.e. explain some variance, reduce entropy, etc.
2. What is gradient boosting trees?
Gradient boosting is a machine …
> update answers to theory.md

- technical.md
Algorithmic Questions, #1. Two sum
> improvement suggestion

- theory.md
Corrected answer to question "How do we check if a variable follows the normal distribution?"
> Kurtosis of normal distribution is 3

- contributors.md
I changed my GitHub username some days ago. I'd appreciate if you can accept the respective change in the contributors file.
> Changed GitHub name from manu183 to manuel-lang

- theory.md
Answer of what happens to our linear model if z is a sum of x and y?
> Add answer to theory.md

- technical.md
A simpler solution with the built in itertools package
> Coding - 11. RLE with itertools.groupby

- technical.md
The solution did not handle duplicated tokens in documents, it has been fixed by converting each document to a set
Another solution is also provided
> Coding - 13 IDF : handle duplicated tokens and add other solution

- theory.md
Answers 3 questions
- What methods for solving linear regression do you know?
- What kind of problems neural nets can solve?
- If a weight for one variable is higher than for another  —  can we say that this variable is more important?
Fixed typos and clarified language in a few other problems.
> Answers to Solving OLS Q and Neural Nets Q

- theory.md
I will be answering more unanswered questions soon.
> added few answers

- technical.md
Fix small typo on line 27: "cound" to "could"
> Fix typo in technical.md

- technical.md
- theory.md
* Add table of contents for `theory.md`
* Add table of contents for `technical.md`
* Close #90
> Create table of contents for markdown files of questions

- theory.md
Answered questions related to learning rate, checkpoints and augmentations.
> Add some answers in theory.md

- theory.md
Added answers in topic neural networks and neural networks for computer vision.
> Add answers in theory.md

- technical.md
> added sum of largest subarray in technical.md

- technical.md
I propose this add.
I don't know how much worth to be in depth to the quantity things, so I had not write numbers down - however, on standard machine, I expect we talk about 1M elements or more.
> add a different solution to remove duplicates

- theory.md
> spell error, reqularization -> regularization

- technical.md
It's O`(n^2)` because in a worth case (all elements are unique) it does `1 + 2 + ... + (n - 1)` comparisons which is `O(n^2)`
> Typo in solution complexity

- theory.md
I have added two answers to intermediate level questions that were previously unanswered in the theory.md file.
> Added gradient boosting model and XGboost answers in theory.md

- technical.md
existing query was not generating the correct date for filtering in where condition
> modified the query to get the answers as expected from the question

- technical.md
modified the answer of question 6 of case 1 to return the results as expected
> modified the answer of question 6 of case 1 in sql questions

- technical.md
modified the question and the query to match the desired output shown in the image
> modified the question and the query to match the desired output

- technical.md
Modified the query to output the results as represented in the image attached with the question.
> modified query to generate the results as expected

- contrib/probability.md
Fixed proposed solution to the coin probability question
> Probability

- theory.md
I noticed there are quite some questions still unanswered, going to try to help a little again :)
> theory: machine learning for text classification

- technical.md
The interview questions is return duplicated value in an array. I hope this can help anyone who find this problem in their technical interview.
> Add my Technical Interview question and the solution about List Comprehension

- awesome.md
Hey, I've added an interview guide to your amazing repos, would love to see it feature in the list:)
> Added a new data science resource

- awesome.md
Add Daily Machine Learning Questions by bnomial
> Daily Machine Learning Questions by bnomial

- theory.md
Answer to What are word embeddings? Why are they useful? Do you know Word2Vec? ‍⭐️
> Answer to word embedding question

- technical.md
Calculating PMI score in acccordance with 'input example'.
> Update PMI Calculation
